### PR TITLE
Add code coverage

### PR DESCRIPTION
**Pull request by sandersky**
#PATCH#

### CODE REVIEW

**Comment by job13er** [comment]
@sandersky I wonder if it's related to this: https://github.com/sglanzer/ember-cli-blanket/issues/124

@sglanzer do you see anything glaringly wrong with the setup of this repo that would cause no `lcov` to report?

**Comment by sglanzer** [comment]
I thought it had LCOV, but was the wrong numbers?  I was going to lean on Jeff for this fix, since he did most of the reporters, but if we're stuck I can try to make some time to dig at this

**Comment by job13er** [comment]
Before it had lcov with wrong numbers, but then you had mentioned it was all fixed, and now it seems to have no lcov. I'll take a look, my current task is getting coverage. So either blanket or istanbul

**Comment by sglanzer** [comment]
I think the remaining issue here is the actual reporter - coverage is being handled and is visible in other formats

**Comment by job13er** [comment]
Cool, I'll take a look at that then

**Comment by NullVoxPopuli** [comment]
are you guys having an issue with coverage being reported when all tests are ran? (but works when a single test is run?)

**Comment by sglanzer** [comment]
I have 30 minutes to poke at this, will let you know what I find

**Comment by sglanzer** [comment]
image

image

**Comment by sglanzer** [comment]
This was run from the browser, I still need to check a CLI execution - @sandersky was this the reporter you wanted?

**Comment by sglanzer** [comment]
image

**Comment by sglanzer** [comment]
Looks like the same coverage report in both cases

image

**Comment by sglanzer** [comment]
I did switch `testem` to use `FireFox` instead of `PhantomJS` (as we typically would do with Travis)

```
{
  "framework": "mocha",
  "test_page": "tests/index.html?hidepassed&coverage",
  "disable_watching": true,
  "launch_in_ci": [
  "FireFox"
  ],
  "launch_in_dev": [
  "FireFox",
  "Chrome"
  ]
}
```

**Comment by sglanzer** [comment]
@sandersky can you comment on the issue you're seeing - when you wake up ;)

**Comment by sglanzer** [comment]
Just for kicks I turned off the click() test and the results:

image

As expected, the 5 lines from onChange are no longer covered

**Comment by sglanzer** [comment]
image

**Pull request merged**
