### PR TITLE
ember-frost-text open-sourced

### PR DESCRIPTION
**Pull request by nskrypnik**

### CODE REVIEW

**Comment by psbanka** [comment]
:shipit:

**Comment by psbanka** [comment]
Approved

**Comment by job13er** [comment]
@nskrypnik This is missing some required changes for an open source project. I've got a branch based off this one that takes it the rest of the way there. Tonight I'm updating your document on converting frost repos to open source and will have an updated PR. You can close this.

**Comment by nskrypnik** [comment]
@job13er OK, I was trying to figure out what's going on, it fails in travis-ci with
```
$ pr-bumper check
No .pr-bumper.json found, using defaults
Using CI commit sha [2fcac518d596a8edd11b1bd62bdae937220d0595]
RO_GH_TOKEN = [undefined]
No PR found for sha [2fcac518d596a8edd11b1bd62bdae937220d0595]
```
Though I'm wondering where does it take sha from. I don't see such sha in any commit. And where does it suppose to take RO_GH_TOKEN? May be something is wrong with generated .travis.yml?

**Comment by job13er** [comment]
The sha comes from the working copy on Travis and it tries to match it against the PR that github returns via the API. There seems to be an issue when the build is triggered by closing and re-opening the PR though. There should be an open issue on the pr-bumper repo about it already. As for that RO token, you have to configure that in Travis, it's mentioned in the confluence doc.

**Pull request closed without merging**
